# Generated by Django 6.0 on 2026-01-06 15:24

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('icon', models.CharField(default='📁', max_length=10, verbose_name='アイコン')),
                ('color', models.CharField(default='gray', max_length=20, verbose_name='色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '支出カテゴリ',
                'verbose_name_plural': '支出カテゴリ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='支払方法名')),
                ('icon', models.CharField(default='💳', max_length=10, verbose_name='アイコン')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '支払方法',
                'verbose_name_plural': '支払方法',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('expense_type', models.CharField(choices=[('personal', '個人'), ('business', '会社')], max_length=20, verbose_name='区分')),
                ('frequency', models.CharField(choices=[('monthly', '毎月'), ('yearly', '毎年')], default='monthly', max_length=20, verbose_name='頻度')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, verbose_name='支払日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='最終生成日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.expensecategory', verbose_name='カテゴリ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.paymentmethod', verbose_name='支払方法')),
            ],
            options={
                'verbose_name': '固定費',
                'verbose_name_plural': '固定費',
                'ordering': ['day_of_month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('expense_type', models.CharField(choices=[('personal', '個人'), ('business', '会社')], max_length=20, verbose_name='区分')),
                ('description', models.CharField(max_length=200, verbose_name='内容')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to=expenses.models.receipt_image_path, verbose_name='レシート画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory', verbose_name='カテゴリ')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.paymentmethod', verbose_name='支払方法')),
                ('recurring_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='expenses.recurringexpense', verbose_name='固定費')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
