# Generated by Django 6.0 on 2026-01-04 09:01

import customers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='会社名')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('name_kana', models.CharField(blank=True, max_length=100, verbose_name='氏名（カナ）')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='携帯番号')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='FAX')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('website', models.URLField(blank=True, verbose_name='Webサイト')),
                ('business_card_front', models.ImageField(blank=True, null=True, upload_to=customers.models.business_card_path, verbose_name='名刺（表）')),
                ('business_card_back', models.ImageField(blank=True, null=True, upload_to=customers.models.business_card_path, verbose_name='名刺（裏）')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('estimate', '見積書'), ('proposal', '提案書'), ('invoice', '請求書'), ('contract', '契約書'), ('web_data', 'Webサイトデータ'), ('photo', '写真'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('file', models.FileField(upload_to=customers.models.customer_directory_path, verbose_name='ファイル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '書類',
                'verbose_name_plural': '書類',
                'ordering': ['-created_at'],
            },
        ),
    ]
