# Generated by Django 6.0 on 2026-01-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='終日')),
                ('color', models.CharField(choices=[('blue', '青'), ('green', '緑'), ('red', '赤'), ('yellow', '黄'), ('purple', '紫'), ('pink', 'ピンク'), ('gray', 'グレー')], default='blue', max_length=20, verbose_name='色')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='customers.customer', verbose_name='関連顧客')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
